/**
 * Nixcord Desktop Injector
 * Patches Discord's _appSettings or preload script to load nixcord.js.
 * We do NOT unpack or repack the .asar — we inject via the preload chain.
 * This is the same approach used by BetterDiscord and Vencord desktop.
 */

import * as fs from "fs";
import * as path from "path";
import * as os from "os";

const INJECTION_MARKER = "/* nixcord-injected */";

interface DiscordInstall {
  name: string;
  resourcesPath: string;
  appPath: string;
}

/**
 * Finds all Discord installations in common Windows locations.
 * Supports Discord Stable only (as requested).
 */
export function findDiscordInstalls(): DiscordInstall[] {
  const found: DiscordInstall[] = [];
  const localAppData = process.env.LOCALAPPDATA ?? path.join(os.homedir(), "AppData", "Local");

  const candidates = [
    { name: "Discord Stable", dir: path.join(localAppData, "Discord") }
  ];

  for (const { name, dir } of candidates) {
    if (!fs.existsSync(dir)) continue;

    // Find the latest app-x.x.x folder
    let versions: string[] = [];
    try {
      versions = fs.readdirSync(dir)
        .filter(d => d.startsWith("app-"))
        .sort()
        .reverse();
    } catch {
      continue;
    }

    for (const version of versions) {
      const resourcesPath = path.join(dir, version, "resources");
      const appPath = path.join(resourcesPath, "app");

      if (fs.existsSync(resourcesPath)) {
        found.push({ name: `${name} (${version})`, resourcesPath, appPath });
        break; // Take only latest version
      }
    }
  }

  return found;
}

/**
 * Returns the path where Nixcord stores its injected app folder.
 * Discord loads from resources/app/ if it exists, bypassing app.asar.
 */
function getNixcordAppDir(install: DiscordInstall): string {
  return install.appPath;
}

/**
 * Returns the path to the Nixcord JS bundle.
 * On production this lives next to the injector executable.
 */
function getNixcordBundlePath(): string {
  return path.join(__dirname, "..", "dist", "nixcord.js");
}

/**
 * Injects Nixcord into a Discord installation.
 * Creates resources/app/ with a shim package.json + index.js that loads
 * the real app.asar AND injects nixcord.js via a preload.
 */
export function inject(install: DiscordInstall): { success: boolean; error?: string } {
  try {
    const appDir = getNixcordAppDir(install);
    const bundlePath = getNixcordBundlePath();

    if (!fs.existsSync(bundlePath)) {
      return { success: false, error: "Nixcord bundle not found. Run the build first." };
    }

    if (isInjected(install)) {
      return { success: false, error: "Nixcord is already injected into this installation." };
    }

    // Create the app directory
    fs.mkdirSync(appDir, { recursive: true });

    // package.json — tells Electron this is a valid app
    const pkgJson = {
      name: "discord",
      main: "index.js",
      version: "1.0.0"
    };
    fs.writeFileSync(
      path.join(appDir, "package.json"),
      JSON.stringify(pkgJson, null, 2)
    );

    // index.js — loads original asar then injects Nixcord preload
    const indexJs = `${INJECTION_MARKER}
// Nixcord Desktop Injector — Generated by NISPAX InfoTech
"use strict";

const path = require("path");
const Module = require("module");

// Patch require to intercept Discord's electron require
// so we can inject our preload before the window is created
const originalLoad = Module._load;
Module._load = function(request, parent, isMain) {
  if (request === "electron") {
    const electron = originalLoad.apply(this, arguments);
    const { BrowserWindow } = electron;

    // Wrap BrowserWindow to inject our preload into every window
    class PatchedBrowserWindow extends BrowserWindow {
      constructor(opts) {
        const nixcordPreload = path.join(__dirname, "preload.js");
        if (opts?.webPreferences) {
          opts.webPreferences._originalPreload = opts.webPreferences.preload;
          opts.webPreferences.preload = nixcordPreload;
        } else {
          opts = { ...opts, webPreferences: { preload: nixcordPreload } };
        }
        super(opts);
      }
    }

    // Copy static methods over
    Object.assign(PatchedBrowserWindow, BrowserWindow);

    return { ...electron, BrowserWindow: PatchedBrowserWindow };
  }

  return originalLoad.apply(this, arguments);
};

// Load Discord's original main process
require(path.join(require("path").dirname(require.resolve(".")), "..", "app.asar"));
`;

    fs.writeFileSync(path.join(appDir, "index.js"), indexJs);

    // preload.js — runs in renderer context, loads Nixcord
    const preloadJs = `
"use strict";

const path = require("path");
const originalPreload = ${JSON.stringify("")}; // replaced at runtime

// Expose a bridge for the renderer to call back into main
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("nixcordBridge", {
  applyUpdate: (script) => ipcRenderer.invoke("nixcord:applyUpdate", script),
  getVersion: () => ipcRenderer.invoke("nixcord:version"),
  platform: "desktop"
});

// Load original preload if there was one
try {
  const orig = process.argv.find(a => a.startsWith("--nixcord-original-preload="));
  if (orig) require(orig.split("=")[1]);
} catch {}

// Inject Nixcord into the page
window.addEventListener("DOMContentLoaded", () => {
  const script = document.createElement("script");
  script.src = "file://" + path.join(__dirname, "nixcord.js").replace(/\\\\/g, "/");
  document.head.appendChild(script);
}, { once: true });
`;

    fs.writeFileSync(path.join(appDir, "preload.js"), preloadJs);

    // Copy the Nixcord bundle into the app dir
    fs.copyFileSync(bundlePath, path.join(appDir, "nixcord.js"));

    console.log(`[Nixcord] Injected into ${install.name} at ${appDir}`);
    return { success: true };
  } catch (err) {
    return { success: false, error: String(err) };
  }
}

/**
 * Removes Nixcord from a Discord installation.
 */
export function uninject(install: DiscordInstall): { success: boolean; error?: string } {
  try {
    const appDir = getNixcordAppDir(install);

    if (!isInjected(install)) {
      return { success: false, error: "Nixcord is not injected into this installation." };
    }

    // Remove the entire app directory — Discord falls back to app.asar
    fs.rmSync(appDir, { recursive: true, force: true });

    console.log(`[Nixcord] Removed from ${install.name}`);
    return { success: true };
  } catch (err) {
    return { success: false, error: String(err) };
  }
}

/**
 * Checks whether Nixcord is currently injected.
 */
export function isInjected(install: DiscordInstall): boolean {
  const indexPath = path.join(install.appPath, "index.js");
  if (!fs.existsSync(indexPath)) return false;
  try {
    return fs.readFileSync(indexPath, "utf-8").includes(INJECTION_MARKER);
  } catch {
    return false;
  }
}

/**
 * Updates the Nixcord bundle in an already-injected installation.
 * Called by the auto-updater after downloading a new build.
 */
export function updateBundle(install: DiscordInstall, newBundlePath: string): { success: boolean; error?: string } {
  try {
    if (!isInjected(install)) {
      return { success: false, error: "Nixcord is not injected — install first." };
    }

    const dest = path.join(install.appPath, "nixcord.js");
    fs.copyFileSync(newBundlePath, dest);
    return { success: true };
  } catch (err) {
    return { success: false, error: String(err) };
  }
}
